name: CI

on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run ci test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: dart pub get
      - run: flutter analyze
      - run: flutter test